### ISSUE TITLE
Affichage des tableaux suivants : matrice des coûts, proposition de transport, table des coûts potentiels, table des coûts marginaux

### ISSUE THREAD

**Issue by mikhailBenali** [mikhailBenali/projet_recherche_operationnelle#2]
# Attention !
La fonction affichage doit être absolument soignée. Toute table comportant des
colonnes qui se décalent sera très lourdement sanctionné. La lisibilité des tables est fondamentale.

**Comment by jmahot** [comment]
Affichage des tableaux terminé
